# Generated by Django 5.1.3 on 2024-12-23 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_classroom_rename_teacher_subject_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
